version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ege_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  telegram_bot:
    build: ./telegram_bot
    environment:
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - backend